#!/usr/bin/env bash

# Install all packages using stow.

declare -a packages=( \
    "alacritty" \
    "bash" \
    "conky" \
    "git" \
    "i3" \
    "nvim" \
    "qpdfview" \
    "tmux" \
    # "vim" \
    # "private" \
)

for package in "${packages[@]}"
do
    echo "$package"
    # -v verbose
    # -R restow (first unstow, then stow again)
    stow -v -R $package
done
